[package]
name = "r-shellitems"
version = "0.0.1"
authors = ["Matthew Seyer <https://github.com/forensicmatt/r-winstructs>"]

[lib]
name = "rshellitems"

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
byteorder = "1"
